import { Metadata } from "next"
export const metadata = {
  title: 'Rakib',
  description: 'Generated by create next app',
}
export async function generateMetadata({ params }: any): Promise<Metadata> {
  return {
    title: 'rakib'
  }
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      {children}
    </>
  )
}

