import Footer from '@/src/components/shared/Footer'
import Navbar from '@/src/components/shared/Navbar/Navbar'


export const metadata = {
  title: 'Rakib',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      {children}
    </>
  )
}
